name: next_template
services:
  next_template:
    container_name: next_template
    image: registry.desarrollosur.com.ar/lautarobarba/next_template:latest
    restart: always
    env_file: .env
    ports:
      - ${FRONT_PORT}:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
